# Generated by Django 5.1.6 on 2025-03-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0002_post_excerpt_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
