# Generated by Django 5.1.6 on 2025-03-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0003_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document')], default='image', max_length=10)),
                ('file', models.FileField(upload_to='media_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
