# Generated by Django 5.1.6 on 2025-04-26 13:28

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0004_mediafile_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='media_files/'),
        ),
    ]
