# Generated by Django 5.1.6 on 2025-04-26 13:28
#
# Historical note: this migration originally pinned the field to
# storages.backends.s3.S3Storage(). Storage is not a database-level attribute,
# so dropping that kwarg leaves the resulting schema identical while removing a
# hard import of the S3 backend from migration history. See website_app/models.py.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0004_mediafile_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(upload_to='media_files/'),
        ),
    ]
