# Generated by Django 5.1.6 on 2025-04-26 14:00
#
# Historical note: this migration originally referenced
# website_app.models.S3FileField(storage=storages.backends.s3.S3Storage()).
# That custom field has been removed — storage now comes solely from
# STORAGES["default"] in settings.py. Storage is not a database-level attribute,
# so the resulting schema is unchanged.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0005_alter_mediafile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(upload_to='media_files/'),
        ),
    ]
