# Generated by Django 5.1.6 on 2025-04-26 14:00

import storages.backends.s3
import website_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0005_alter_mediafile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=website_app.models.S3FileField(storage=storages.backends.s3.S3Storage(), upload_to='media_files/'),
        ),
    ]
