# Generated by Django 5.1.6 on 2025-05-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0006_alter_mediafile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
