# Generated by Django 5.1.6 on 2025-06-09 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0007_mediafile_file_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='file_size',
        ),
    ]
