# Generated by Django 5.1.6 on 2025-06-10 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0008_remove_mediafile_file_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
    ]
