# Generated by Django 5.2.17 on 2026-08-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0009_remove_post_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('audio', 'Audio')], default='image', max_length=10),
        ),
    ]
