# Generated by Django 5.2.13 on 2026-08-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='path',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
