# Generated by Django 5.1.6 on 2025-04-10 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_task_delete_todolist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
